### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by nwilliams770** [nwilliams770/tyrello#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
The overall ui and design looks beautiful. There is currently a problem rendering the errors on the heroku hosted site. Once that is figured out, we can test and close this issue.

**Comment by anastassia-b** [comment]
Additional things to note:
- [x] sign up button is a different case 
- [x] styling errors
- [x] clearing errors when switching between forms
- [x] repushing to heroku

**Comment by anastassia-b** [comment]
Excellent, this MVP is complete.
