### ISSUE TITLE
PA Review: Boards

### ISSUE THREAD

**Issue by nwilliams770** [nwilliams770/tyrello#3]
- [x] Board index page displays boards of current user
- [x] User can add new board
- [x] User can navigate to board show page via board buttons
- [x] Styled and bug-free

**Comment by anastassia-b** [comment]
The Boards index is coming along well. The layout is good, with the nav bar and dropdown. I can't create a board without a name, and when I do, the form works well. One point to consider is the density of blues on the page-- it could do with some lightening up, or more contrast (as was demonstrated on your welcome page). 
- [x] Decrease blue density

**Comment by anastassia-b** [comment]
- [x] Remove the dropdown OR just have it be a button which pushes to /boards.
- [x] Add background image to show page and make styling acceptable.
- [x] Push to heroku
- [x] Branch it
- [x] Make your app ready for production in original branch. 
- [x] Final push to heroku. 
- [ ] Write the README. 
- [ ] If time, work on the branch to mainly fix adding a card and re-rendering the component.
